/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Nat;
export const Size = IDL.Variant({
  'L' : IDL.Null,
  'M' : IDL.Null,
  'S' : IDL.Null,
  'XL' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'size' : Size,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'stripePaymentId' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'stripePaymentId' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
});
export const Category = IDL.Variant({
  'BestSellers' : IDL.Null,
  'Trending' : IDL.Null,
  'NewArrivals' : IDL.Null,
});
export const CreateProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Size),
  'stock' : IDL.Vec(IDL.Tuple(Size, IDL.Nat)),
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Size),
  'stock' : IDL.Vec(IDL.Tuple(Size, IDL.Nat)),
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'size' : Size,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const NewsletterSubscription = IDL.Record({
  'subscribedAt' : Timestamp,
  'email' : IDL.Text,
});
export const UpdateProductInput = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'sizes' : IDL.Opt(IDL.Vec(Size)),
  'stock' : IDL.Opt(IDL.Vec(IDL.Tuple(Size, IDL.Nat))),
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'price' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addToCart' : IDL.Func([ProductId, Size, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'createProduct' : IDL.Func([CreateProductInput], [Product], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscription)],
      ['query'],
    ),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([ProductId, Size], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'searchProducts' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(Category),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateCartQuantity' : IDL.Func([ProductId, Size, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func(
      [ProductId, UpdateProductInput],
      [IDL.Opt(Product)],
      [],
    ),
  'updateStock' : IDL.Func([ProductId, Size, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Nat;
  const Size = IDL.Variant({
    'L' : IDL.Null,
    'M' : IDL.Null,
    'S' : IDL.Null,
    'XL' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'size' : Size,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'stripePaymentId' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'stripePaymentId' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
  });
  const Category = IDL.Variant({
    'BestSellers' : IDL.Null,
    'Trending' : IDL.Null,
    'NewArrivals' : IDL.Null,
  });
  const CreateProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Size),
    'stock' : IDL.Vec(IDL.Tuple(Size, IDL.Nat)),
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Size),
    'stock' : IDL.Vec(IDL.Tuple(Size, IDL.Nat)),
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'size' : Size,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const NewsletterSubscription = IDL.Record({
    'subscribedAt' : Timestamp,
    'email' : IDL.Text,
  });
  const UpdateProductInput = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'sizes' : IDL.Opt(IDL.Vec(Size)),
    'stock' : IDL.Opt(IDL.Vec(IDL.Tuple(Size, IDL.Nat))),
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'price' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addToCart' : IDL.Func([ProductId, Size, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'createProduct' : IDL.Func([CreateProductInput], [Product], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscription)],
        ['query'],
      ),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([ProductId, Size], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'searchProducts' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(Category),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateCartQuantity' : IDL.Func([ProductId, Size, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func(
        [ProductId, UpdateProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'updateStock' : IDL.Func([ProductId, Size, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };