/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'size' : Size,
  'productId' : ProductId,
  'quantity' : bigint,
}
export type Category = { 'BestSellers' : null } |
  { 'Trending' : null } |
  { 'NewArrivals' : null };
export interface CreateOrderInput {
  'stripePaymentId' : string,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
}
export interface CreateProductInput {
  'name' : string,
  'description' : string,
  'sizes' : Array<Size>,
  'stock' : Array<[Size, bigint]>,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface DashboardStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'totalRevenue' : bigint,
}
export interface NewsletterSubscription {
  'subscribedAt' : Timestamp,
  'email' : string,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'stripePaymentId' : string,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'size' : Size,
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'sizes' : Array<Size>,
  'stock' : Array<[Size, bigint]>,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
}
export type Size = { 'L' : null } |
  { 'M' : null } |
  { 'S' : null } |
  { 'XL' : null };
export type Timestamp = bigint;
export interface UpdateProductInput {
  'name' : [] | [string],
  'description' : [] | [string],
  'sizes' : [] | [Array<Size>],
  'stock' : [] | [Array<[Size, bigint]>],
  'imageUrl' : [] | [string],
  'category' : [] | [Category],
  'price' : [] | [bigint],
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToCart' : ActorMethod<[ProductId, Size, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'createProduct' : ActorMethod<[CreateProductInput], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<NewsletterSubscription>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[ProductId, Size], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'searchProducts' : ActorMethod<
    [[] | [string], [] | [Category], [] | [bigint], [] | [bigint]],
    Array<Product>
  >,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'updateCartQuantity' : ActorMethod<[ProductId, Size, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<
    [ProductId, UpdateProductInput],
    [] | [Product]
  >,
  'updateStock' : ActorMethod<[ProductId, Size, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];